=== ASTRIX285/ASTRIXPARADOX.github.io/astrix-app/games/wow-forever/data/schema/talent-tree.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://astrixparadox.com/astrix-app/games/wow-forever/data/schema/talent-tree.schema.json",
  "title": "Forever talent tree",
  "type": "object",
  "required": ["id", "name", "classIds", "order", "talents", "provenance"],
  "additionalProperties": false,
  "properties": {
    "id": { "type": "integer" },
    "name": { "oneOf": [{ "type": "string" }, { "$ref": "pending.schema.json" }] },
    "classIds": { "type": "array", "items": { "type": "integer" }, "description": "Decoded from the ClassMask column: bit (classId - 1)." },
    "order": { "oneOf": [{ "type": "integer" }, { "$ref": "pending.schema.json" }] },
    "talents": { "type": "array", "items": { "$ref": "talent.schema.json" } },
    "provenance": { "$ref": "provenance.schema.json" }
  }
}

=== ASTRIX285/ASTRIXPARADOX.github.io/astrix-app/games/wow-forever/data/generated/talentTrees.json
[{"id":41,"name":"Fire","classIds":[8],"order":1,"talents":[{"id":23,"treeId":41,"row":2,"column":3,"rankSpellIds":[11083,12351],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":23,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":24,"treeId":41,"row":3,"column":1,"rankSpellIds":[11094,13043],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":24,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":25,"treeId":41,"row":3,"column":0,"rankSpellIds":[11095,12872,12873],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":25,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":26,"treeId":41,"row":0,"column":1,"rankSpellIds":[11069,12338,12339,12340,12341],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":26,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":27,"treeId":41,"row":1,"column":2,"rankSpellIds":[11078,11080,12342],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":27,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":28,"treeId":41,"row":1,"column":1,"rankSpellIds":[11100,12353],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":28,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":29,"treeId":41,"row":2,"column":2,"rankSpellIds":[11366],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":29,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":30,"treeId":41,"row":0,"column":2,"rankSpellIds":[11103,12357,12358,12359,12360],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":30,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":31,"treeId":41,"row":2,"column":1,"rankSpellIds":[11108,12349,12350],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":31,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":32,"treeId":41,"row":4,"column":2,"rankSpellIds":[11113],"prerequisites":[{"talentId":29,"rank":1}],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":32,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":33,"treeId":41,"row":4,"column":1,"rankSpellIds":[11115,11367,11368],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":33,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":34,"treeId":41,"row":1,"column":0,"rankSpellIds":[11119,11120,12846,12847,12848],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":34,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":35,"treeId":41,"row":5,"column":2,"rankSpellIds":[11124,12378,12398,12399,12400],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":35,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":36,"treeId":41,"row":6,"column":1,"rankSpellIds":[11129],"prerequisites":[{"talentId":33,"rank":3}],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":36,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":1141,"treeId":41,"row":2,"column":0,"rankSpellIds":[18459,18460],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":1141,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":1639,"treeId":41,"row":3,"column":3,"rankSpellIds":[29074,29075,29076],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":1639,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}}],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"TalentTab","rowId":41,"sourceSha256":"9539a388c0e697381f7574247488da528f2647099db4c39096bdb2a8695139b9"}},{"id":61,"name":"Frost","classIds":[8],"order":2,"talents":[{"id":37,"treeId":61,"row":0,"column":1,"rankSpellIds":[11070,12473,16763,16765,16766],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":37,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":38,"treeId":61,"row":1,"column":1,"rankSpellIds":[11071,12496,12497],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":38,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":61,"treeId":61,"row":2,"column":0,"rankSpellIds":[11151,12952,12953],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":61,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":62,"treeId":61,"row":1,"column":2,"rankSpellIds":[11165,12475],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":62,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":63,"treeId":61,"row":2,"column":3,"rankSpellIds":[11185,12487,12488],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":63,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":64,"treeId":61,"row":4,"column":2,"rankSpellIds":[11190,12489,12490],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":64,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":65,"treeId":61,"row":1,"column":3,"rankSpellIds":[11175,12569,12571],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":65,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":66,"treeId":61,"row":3,"column":1,"rankSpellIds":[11160,12518,12519],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":66,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":67,"treeId":61,"row":3,"column":2,"rankSpellIds":[11170,12982,12983,12984,12985],"prerequisites":[{"talentId":62,"rank":2}],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":67,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":68,"treeId":61,"row":5,"column":2,"rankSpellIds":[11180,28592,28593,28594,28595],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":68,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":69,"treeId":61,"row":2,"column":1,"rankSpellIds":[12472],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":69,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":70,"treeId":61,"row":0,"column":0,"rankSpellIds":[11189,28332],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":70,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":71,"treeId":61,"row":6,"column":1,"rankSpellIds":[11426],"prerequisites":[{"talentId":72,"rank":1}],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":71,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":72,"treeId":61,"row":4,"column":1,"rankSpellIds":[11958],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":72,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":73,"treeId":61,"row":1,"column":0,"rankSpellIds":[11207,12672,15047,15052,15053],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":73,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":741,"treeId":61,"row":3,"column":0,"rankSpellIds":[16757,16758],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":741,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":1649,"treeId":61,"row":0,"column":2,"rankSpellIds":[29438,29439,29440],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":1649,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}}],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"TalentTab","rowId":61,"sourceSha256":"9539a388c0e697381f7574247488da528f2647099db4c39096bdb2a8695139b9"}},{"id":81,"name":"Arcane","classIds":[8],"order":0,"talents":[{"id":74,"treeId":81,"row":0,"column":0,"rankSpellIds":[11210,12592],"prerequisites":[],"provenance":{"product":"wow_classic_beta","build":"1.60.1.70094","table":"Talent","rowId":74,"sourceSha256":"ef5518c5a3aaa7458e074a7e41e87837f8a1c74da00938244019e2e8c0428b4a"}},{"id":75,"treeId":81,"row":1,"column":2,"rankSpellIds":[11213,12574,12575,12576,12577],"prerequisites":[],"provenance":{"
